import { createLlmClient } from '@/lib/llm';
import { recommendationService } from '@/services/recommendationService';
import { goalService } from '@/services/goalService';
import { benchmarkService } from '@/services/benchmarkService';
import { reportService } from '@/services/reportService';
import { kpiService } from '@/services/kpiService';
import { db } from '@/db';
import { reportingPeriods } from '@/db/schema';
import { eq, desc } from 'drizzle-orm';
import { logger } from '@/lib/logger';
import type { AskAiBody } from '@/schemas/askAi';

// ── Types ────────────────────────────────────────────────────

export interface AskAiResponse {
  answer: string;
  dataSources: string[];
  disclaimer: string;
}

// ── Keyword matchers ─────────────────────────────────────────

const BENCHMARK_KEYWORDS = /\b(peer|benchmark|compare|sector|rank|percentile|quartile)\b/i;
const KPI_KEYWORDS = /\b(ghg|emission|energy|water|waste|intensity|scope|carbon)\b/i;
const COVERAGE_KEYWORDS = /\b(coverage|compliance|disclosure|brsr|esrs|gri|ifrs|report)\b/i;

// ── Context helpers ──────────────────────────────────────────

async function safeCall<T>(label: string, fn: () => Promise<T>): Promise<T | null> {
  try {
    return await fn();
  } catch (err) {
    logger.warn(`AskAI: ${label} context fetch failed`, {
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}

function formatRecommendations(recs: Awaited<ReturnType<typeof recommendationService.getRecommendations>>): string {
  if (recs.length === 0) return 'No recommendations available.';
  return recs.slice(0, 10).map((r, i) =>
    `${i + 1}. [${r.priority}] ${r.metric}: ${r.recommendationText}`
  ).join('\n');
}

function formatGoals(goals: Awaited<ReturnType<typeof goalService.list>>): string {
  if (goals.data.length === 0) return 'No active goals.';
  return goals.data.slice(0, 10).map(g =>
    `- ${g.name}: ${g.status} (progress: ${g.progress}%)`
  ).join('\n');
}

// ── Main service ─────────────────────────────────────────────

const SYSTEM_PROMPT = `You are GreenMeter AI, an ESG data analyst for a sustainability reporting platform.
Answer using ONLY the provided tenant data. Follow these rules strictly:
- Never invent or estimate numbers not in the data
- Be concise and use bullet points
- Cite which data source you used (e.g., "Based on recommendations data..." or "From KPI values...")
- Do not provide legal, financial, or investment advice
- If the data doesn't contain enough information to answer, say so clearly`;

const DISCLAIMER = 'This response is generated by AI based on available ESG data. It does not constitute professional advice. Always verify critical data with authoritative sources.';

export const askAiService = {
  async ask(
    tenantId: string,
    body: AskAiBody
  ): Promise<AskAiResponse> {
    const { question, context } = body;
    const dataSources: string[] = [];
    const contextSections: string[] = [];

    // Always include: recommendations and goals (lightweight, always relevant)
    const [recs, goals] = await Promise.allSettled([
      safeCall('recommendations', () => recommendationService.getRecommendations(tenantId, 10)),
      safeCall('goals', () => goalService.list(tenantId, { page: 1, pageSize: 20 })),
    ]);

    if (recs.status === 'fulfilled' && recs.value) {
      contextSections.push(`=== TOP RECOMMENDATIONS ===\n${formatRecommendations(recs.value)}`);
      dataSources.push('Recommendations');
    }

    if (goals.status === 'fulfilled' && goals.value) {
      contextSections.push(`=== ACTIVE GOALS ===\n${formatGoals(goals.value)}`);
      dataSources.push('Goals');
    }

    // Conditionally include based on keywords in the question
    const conditionalFetches: Promise<void>[] = [];

    if (BENCHMARK_KEYWORDS.test(question)) {
      conditionalFetches.push(
        (async () => {
          const benchmark = await safeCall('benchmark', () =>
            benchmarkService.getBenchmark(tenantId, 'ghg_scope1_intensity', 'FY2024')
          );
          if (benchmark && !benchmark.insufficientData) {
            const pctRank = benchmark.percentileRank != null ? `${Math.round(benchmark.percentileRank)}th percentile` : 'no rank';
            contextSections.push(
              `=== BENCHMARK: ${benchmark.canonicalName} ===\nTenant value: ${benchmark.tenantValue}, Sector median: ${benchmark.sectorMedian}, Rank: ${pctRank}, Peers: ${benchmark.peerCount}`
            );
            dataSources.push('Benchmarks');
          }
        })()
      );
    }

    if (KPI_KEYWORDS.test(question)) {
      conditionalFetches.push(
        (async () => {
          const kpis = await safeCall('kpi-values', () =>
            kpiService.listValues(tenantId, { page: 1, pageSize: 20 })
          );
          if (kpis?.data && kpis.data.length > 0) {
            const lines = kpis.data.slice(0, 15).map(v =>
              `- ${v.paramName ?? v.paramId}: ${v.value ?? v.valueText ?? 'N/A'} (${v.ragStatus})`
            );
            contextSections.push(`=== KPI VALUES ===\n${lines.join('\n')}`);
            dataSources.push('KPI Values');
          }
        })()
      );
    }

    if (COVERAGE_KEYWORDS.test(question)) {
      conditionalFetches.push(
        (async () => {
          // Resolve the latest period to get a real periodId
          const periods = await safeCall('resolve-periods', async () => {
            const rows = await db
              .select({ periodId: reportingPeriods.periodId })
              .from(reportingPeriods)
              .where(eq(reportingPeriods.tenantId, tenantId))
              .orderBy(desc(reportingPeriods.startDate))
              .limit(1);
            return rows[0]?.periodId ?? null;
          });
          if (!periods) return;

          for (const fw of ['brsr', 'gri', 'esrs']) {
            const cov = await safeCall('coverage-' + fw, () =>
              reportService.getCoverage(fw, tenantId, periods)
            );
            if (cov) {
              contextSections.push(
                `=== ${fw.toUpperCase()} COVERAGE ===\n${Math.round(cov.percentComplete)}% complete (${cov.hasValue}/${cov.totalParams} params). Below threshold: ${cov.belowThreshold}`
              );
              dataSources.push(`${fw.toUpperCase()} Coverage`);
            }
          }
        })()
      );
    }

    await Promise.allSettled(conditionalFetches);

    // Build prompt
    const contextBlock = contextSections.length > 0
      ? `--- TENANT DATA ---\n${contextSections.join('\n\n')}\n--- END ---`
      : '--- TENANT DATA ---\nNo data available for this tenant.\n--- END ---';

    const contextHint = context === 'industry'
      ? '\nThe user is viewing the Industry Data screen, comparing peer organisations.'
      : context === 'analytics'
        ? '\nThe user is viewing the Analytics screen, analysing their own ESG performance.'
        : '';

    const userInput = `${contextBlock}${contextHint}\n\nQuestion: ${question}`;

    // Call LLM
    const llm = createLlmClient();
    const answer = await llm.complete(SYSTEM_PROMPT, userInput, {
      temperature: 0.3,
      maxTokens: 1024,
    });

    return {
      answer,
      dataSources,
      disclaimer: DISCLAIMER,
    };
  },
};
