import PDFDocument from 'pdfkit';
import type { RenderedReport, RenderedSection, RenderedDisclosure, RenderedParameter } from '@/services/reportService';

const COLORS = {
  primary: '#0d9488',      // teal-600
  headerBg: '#f0fdfa',     // teal-50
  text: '#1e293b',         // slate-800
  textMuted: '#64748b',    // slate-500
  border: '#e2e8f0',       // slate-200
  reported: '#059669',     // emerald-600
  notReported: '#dc2626',  // red-600
  notApplicable: '#9ca3af', // gray-400
  verified: '#0d9488',     // teal-600
} as const;

const FONTS = {
  header: 'Helvetica-Bold',
  body: 'Helvetica',
  bodyBold: 'Helvetica-Bold',
} as const;

const PAGE = {
  marginTop: 60,
  marginBottom: 60,
  marginLeft: 50,
  marginRight: 50,
  width: 612,   // US Letter
  height: 792,
} as const;

const CONTENT_WIDTH = PAGE.width - PAGE.marginLeft - PAGE.marginRight;

/**
 * Generates a PDF buffer from a RenderedReport.
 *
 * Uses pdfkit (no browser/puppeteer dependency) to produce a structured
 * disclosure report suitable for regulatory filing.
 *
 * @returns A Promise resolving to a Buffer containing the PDF bytes.
 */
export async function generatePdfFromReport(report: RenderedReport): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Uint8Array[] = [];

    const doc = new PDFDocument({
      size: 'LETTER',
      margins: {
        top: PAGE.marginTop,
        bottom: PAGE.marginBottom,
        left: PAGE.marginLeft,
        right: PAGE.marginRight,
      },
      info: {
        Title: `${report.templateName} — ${report.fiscalYear}`,
        Author: 'GreenMeter AI',
        Subject: `ESG Report — ${report.framework}`,
        Creator: 'GreenMeter AI Platform',
      },
      bufferPages: true,
    });

    doc.on('data', (chunk: Uint8Array) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    try {
      renderCoverPage(doc, report);
      renderTableOfContents(doc, report);

      for (const section of report.sections) {
        renderSection(doc, section, report.framework);
      }

      renderSummaryPage(doc, report);
      addPageNumbers(doc);
    } catch (renderError) {
      doc.destroy();
      reject(renderError);
      return;
    }

    doc.end();
  });
}

function renderCoverPage(doc: PDFKit.PDFDocument, report: RenderedReport): void {
  doc.fontSize(28)
    .font(FONTS.header)
    .fillColor(COLORS.primary)
    .text(report.templateName, PAGE.marginLeft, 200, {
      width: CONTENT_WIDTH,
      align: 'center',
    });

  doc.moveDown(0.5)
    .fontSize(18)
    .font(FONTS.body)
    .fillColor(COLORS.text)
    .text(`Fiscal Year ${report.fiscalYear}`, { align: 'center' });

  doc.moveDown(2)
    .fontSize(11)
    .fillColor(COLORS.textMuted)
    .text(`Framework: ${report.framework}`, { align: 'center' })
    .text(`Template Version: ${report.templateVersion}`, { align: 'center' })
    .text(`Generated: ${new Date(report.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' });

  doc.moveDown(3);

  // Coverage summary box
  const boxX = PAGE.marginLeft + 100;
  const boxWidth = CONTENT_WIDTH - 200;
  const boxY = doc.y;

  doc.rect(boxX, boxY, boxWidth, 80)
    .lineWidth(1)
    .strokeColor(COLORS.border)
    .stroke();

  doc.fontSize(12)
    .font(FONTS.bodyBold)
    .fillColor(COLORS.text)
    .text('Coverage Summary', boxX + 10, boxY + 10, { width: boxWidth - 20, align: 'center' });

  doc.fontSize(10)
    .font(FONTS.body)
    .fillColor(COLORS.textMuted)
    .text(
      `Reported: ${report.coverage.reported} | Not Reported: ${report.coverage.notReported} | N/A: ${report.coverage.notApplicable} | Total: ${report.coverage.total}`,
      boxX + 10, boxY + 32, { width: boxWidth - 20, align: 'center' }
    )
    .text(
      `Completion: ${report.coverage.percentComplete}%`,
      boxX + 10, boxY + 50, { width: boxWidth - 20, align: 'center' }
    );

  doc.fontSize(8)
    .fillColor(COLORS.textMuted)
    .text('Generated by GreenMeter AI', PAGE.marginLeft, PAGE.height - 100, {
      width: CONTENT_WIDTH,
      align: 'center',
    });
}

function renderTableOfContents(doc: PDFKit.PDFDocument, report: RenderedReport): void {
  doc.addPage();

  doc.fontSize(18)
    .font(FONTS.header)
    .fillColor(COLORS.primary)
    .text('Table of Contents', PAGE.marginLeft, PAGE.marginTop);

  doc.moveDown(1);

  for (let i = 0; i < report.sections.length; i++) {
    const section = report.sections[i];
    const sectionNum = i + 1;
    const coverageText = section.total > 0
      ? `${section.reported}/${section.total} reported`
      : 'No parameters';

    ensureSpace(doc, 20);

    doc.fontSize(11)
      .font(FONTS.bodyBold)
      .fillColor(COLORS.text)
      .text(`${sectionNum}. ${section.name}`, PAGE.marginLeft, doc.y, {
        continued: true,
        width: CONTENT_WIDTH - 120,
      });

    doc.font(FONTS.body)
      .fillColor(COLORS.textMuted)
      .text(`  ${coverageText}`, { align: 'right' });

    if (section.disclosures.length > 0) {
      for (const disclosure of section.disclosures) {
        ensureSpace(doc, 14);
        doc.fontSize(9)
          .font(FONTS.body)
          .fillColor(COLORS.textMuted)
          .text(`    ${disclosure.name} (${disclosure.reported}/${disclosure.total})`, PAGE.marginLeft + 20);
      }
    }

    doc.moveDown(0.3);
  }
}

function ensureSpace(doc: PDFKit.PDFDocument, needed: number): void {
  const available = PAGE.height - PAGE.marginBottom - doc.y;
  if (available < needed) {
    doc.addPage();
  }
}

function renderSection(doc: PDFKit.PDFDocument, section: RenderedSection, framework: string): void {
  doc.addPage();

  // Section header
  doc.rect(PAGE.marginLeft, PAGE.marginTop - 5, CONTENT_WIDTH, 30)
    .fill(COLORS.headerBg);

  doc.fontSize(14)
    .font(FONTS.header)
    .fillColor(COLORS.primary)
    .text(section.name, PAGE.marginLeft + 10, PAGE.marginTop + 2, {
      width: CONTENT_WIDTH - 20,
    });

  doc.moveDown(0.5);

  if (section.pillar) {
    doc.fontSize(9)
      .font(FONTS.body)
      .fillColor(COLORS.textMuted)
      .text(`Pillar: ${section.pillar} | Framework: ${framework}`, PAGE.marginLeft + 10);
  }

  if (section.description) {
    doc.fontSize(9)
      .font(FONTS.body)
      .fillColor(COLORS.textMuted)
      .text(section.description, PAGE.marginLeft + 10, doc.y + 2, {
        width: CONTENT_WIDTH - 20,
      });
  }

  doc.moveDown(0.5);

  // Section coverage bar
  doc.fontSize(9)
    .font(FONTS.bodyBold)
    .fillColor(COLORS.text)
    .text(`Coverage: ${section.reported}/${section.total} parameters reported`, PAGE.marginLeft + 10);

  doc.moveDown(0.8);

  for (const disclosure of section.disclosures) {
    renderDisclosure(doc, disclosure);
  }
}

function renderDisclosure(doc: PDFKit.PDFDocument, disclosure: RenderedDisclosure): void {
  ensureSpace(doc, 60);

  // Disclosure sub-header
  doc.fontSize(11)
    .font(FONTS.bodyBold)
    .fillColor(COLORS.text)
    .text(disclosure.name, PAGE.marginLeft + 5);

  if (disclosure.description) {
    doc.fontSize(8)
      .font(FONTS.body)
      .fillColor(COLORS.textMuted)
      .text(disclosure.description, PAGE.marginLeft + 5, doc.y, {
        width: CONTENT_WIDTH - 10,
      });
  }

  doc.moveDown(0.3);

  if (disclosure.parameters.length === 0) {
    doc.fontSize(8)
      .font(FONTS.body)
      .fillColor(COLORS.textMuted)
      .text('No parameters in this disclosure.', PAGE.marginLeft + 10);
    doc.moveDown(0.5);
    return;
  }

  // Table header
  renderParameterTableHeader(doc);

  for (const param of disclosure.parameters) {
    renderParameterRow(doc, param);
  }

  doc.moveDown(0.5);

  // Disclosure summary
  doc.fontSize(8)
    .font(FONTS.body)
    .fillColor(COLORS.textMuted)
    .text(
      `${disclosure.reported}/${disclosure.total} parameters reported`,
      PAGE.marginLeft + 5
    );

  doc.moveDown(0.8);
}

function renderParameterTableHeader(doc: PDFKit.PDFDocument): void {
  ensureSpace(doc, 30);

  const y = doc.y;
  const col = getColumnPositions();

  doc.rect(PAGE.marginLeft, y - 2, CONTENT_WIDTH, 16)
    .fill('#f1f5f9'); // slate-100

  doc.fontSize(7)
    .font(FONTS.bodyBold)
    .fillColor(COLORS.text);

  doc.text('Code', col.code, y, { width: col.codeW });
  doc.text('Parameter', col.name, y, { width: col.nameW });
  doc.text('Value', col.value, y, { width: col.valueW });
  doc.text('Unit', col.unit, y, { width: col.unitW });
  doc.text('Status', col.status, y, { width: col.statusW });

  doc.y = y + 16;
}

function getColumnPositions() {
  const x = PAGE.marginLeft;
  return {
    code: x + 5,
    codeW: 55,
    name: x + 65,
    nameW: 200,
    value: x + 270,
    valueW: 110,
    unit: x + 385,
    unitW: 50,
    status: x + 440,
    statusW: 70,
  };
}

function renderParameterRow(doc: PDFKit.PDFDocument, param: RenderedParameter): void {
  ensureSpace(doc, 24);

  const y = doc.y;
  const col = getColumnPositions();

  // Alternate row background
  doc.rect(PAGE.marginLeft, y - 1, CONTENT_WIDTH, 14)
    .fill('#ffffff');

  doc.fontSize(7)
    .font(FONTS.body)
    .fillColor(COLORS.text);

  doc.text(param.code, col.code, y, { width: col.codeW, lineBreak: false });
  doc.text(truncate(param.name, 45), col.name, y, { width: col.nameW, lineBreak: false });

  // Value with color based on status
  const valueColor = param.status === 'reported' ? COLORS.text
    : param.status === 'not_applicable' ? COLORS.notApplicable
    : COLORS.notReported;

  doc.fillColor(valueColor)
    .text(truncate(param.displayValue, 25), col.value, y, { width: col.valueW, lineBreak: false });

  doc.fillColor(COLORS.textMuted)
    .text(param.unit || '-', col.unit, y, { width: col.unitW, lineBreak: false });

  // Status badge
  const statusColor = param.status === 'reported' ? COLORS.reported
    : param.status === 'not_applicable' ? COLORS.notApplicable
    : COLORS.notReported;
  const statusLabel = param.status === 'reported'
    ? (param.verified ? 'Verified' : 'Reported')
    : param.status === 'not_applicable' ? 'N/A'
    : 'Missing';

  doc.fillColor(statusColor)
    .font(FONTS.bodyBold)
    .text(statusLabel, col.status, y, { width: col.statusW, lineBreak: false });

  doc.y = y + 14;
}

function renderSummaryPage(doc: PDFKit.PDFDocument, report: RenderedReport): void {
  doc.addPage();

  doc.fontSize(18)
    .font(FONTS.header)
    .fillColor(COLORS.primary)
    .text('Report Summary', PAGE.marginLeft, PAGE.marginTop);

  doc.moveDown(1);

  // Overall stats
  const stats = [
    ['Framework', report.framework],
    ['Template', report.templateName],
    ['Fiscal Year', report.fiscalYear],
    ['Generated', new Date(report.generatedAt).toLocaleString('en-US')],
    ['Total Parameters', String(report.coverage.total)],
    ['Reported', String(report.coverage.reported)],
    ['Not Reported', String(report.coverage.notReported)],
    ['Not Applicable', String(report.coverage.notApplicable)],
    ['Completion', `${report.coverage.percentComplete}%`],
  ];

  for (const [label, value] of stats) {
    doc.fontSize(10)
      .font(FONTS.bodyBold)
      .fillColor(COLORS.text)
      .text(`${label}: `, PAGE.marginLeft + 10, doc.y, { continued: true });

    doc.font(FONTS.body)
      .fillColor(COLORS.textMuted)
      .text(value);
  }

  doc.moveDown(1.5);

  // Per-section summary table
  doc.fontSize(12)
    .font(FONTS.bodyBold)
    .fillColor(COLORS.text)
    .text('Section Coverage', PAGE.marginLeft + 10);

  doc.moveDown(0.5);

  for (const section of report.sections) {
    const pct = section.total > 0
      ? Math.round((section.reported / section.total) * 100)
      : 0;

    doc.fontSize(9)
      .font(FONTS.body)
      .fillColor(COLORS.text)
      .text(`${section.name}`, PAGE.marginLeft + 20, doc.y, {
        continued: true,
        width: 300,
      });

    const pctColor = pct >= 80 ? COLORS.reported : pct >= 50 ? '#d97706' : COLORS.notReported;
    doc.fillColor(pctColor)
      .text(`${section.reported}/${section.total} (${pct}%)`, {
        align: 'right',
        width: CONTENT_WIDTH - 320,
      });
  }

  doc.moveDown(2);

  doc.fontSize(8)
    .font(FONTS.body)
    .fillColor(COLORS.textMuted)
    .text(
      'This report was generated by GreenMeter AI. The data reflects the state of KPI entries at the time of generation.',
      PAGE.marginLeft + 10,
      doc.y,
      { width: CONTENT_WIDTH - 20, align: 'center' }
    );
}

function addPageNumbers(doc: PDFKit.PDFDocument): void {
  const pages = doc.bufferedPageRange();
  for (let i = pages.start; i < pages.start + pages.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(8)
      .font(FONTS.body)
      .fillColor(COLORS.textMuted)
      .text(
        `Page ${i + 1} of ${pages.count}`,
        PAGE.marginLeft,
        PAGE.height - 35,
        { width: CONTENT_WIDTH, align: 'center' }
      );
  }
}

function truncate(text: string | null | undefined, maxLen: number): string {
  if (!text) return '';
  if (text.length <= maxLen) return text;
  return text.slice(0, maxLen - 1) + '\u2026';
}
